## Problem Statement 14: 
Locate dataset (e.g., sample_weather.txt) for working on weather data which reads the text input files 
and finds average for temperature, dew point and wind speed year wise/month-wise.

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('Datasets/weather_data.csv')
df.describe(include='all')

,date,time,temperature,dew_point,humidity,wind,wind_speed,wind_gust,pressure,precip,condition,city,country
count,12960,12960,12960.000000,12960.000000,12960.000000,12936,12960.000000,12960.000000,12960.000000,12960.0,12960,12960,12960
unique,273,116,NaN,NaN,NaN,18,NaN,NaN,NaN,NaN,25,1,1
top,2020-01-1,2:30 PM,NaN,NaN,NaN,WSW,NaN,NaN,NaN,NaN,Fair,Karachi,Pakistan
freq,86,257,NaN,NaN,NaN,2403,NaN,NaN,NaN,NaN,4541,12960,12960
mean,NaN,NaN,73.748765,51.149846,50.276698,NaN,7.893596,0.002238,29.816519,0.0,NaN,NaN,NaN
std,NaN,NaN,11.809828,15.927233,22.003563,NaN,4.903547,0.254739,1.091076,0.0,NaN,NaN,NaN
min,NaN,NaN,0.000000,-29.000000,0.000000,NaN,0.000000,0.000000,0.000000,0.0,NaN,NaN,NaN
25%,NaN,NaN,64.000000,39.000000,33.000000,NaN,5.000000,0.000000,29.750000,0.0,NaN,NaN,NaN
50%,NaN,NaN,75.000000,52.000000,50.000000,NaN,7.000000,0.000000,29.890000,0.0,NaN,NaN,NaN
75%,NaN,NaN,82.000000,64.000000,69.000000,NaN,10.000000,0.000000,29.980000,0.0,NaN,NaN,NaN
max,NaN,NaN,106.000000,81.000000,100.000000,NaN,37.000000,29.000000,31.780000,0.0,NaN,NaN,NaN

In [5]:
df['datetime'] = pd.to_datetime(df['date']+' '+df['time'])

C:\Users\DELL\AppData\Local\Temp\ipykernel_25252\2783538227.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['datetime'] = pd.to_datetime(df['date']+' '+df['time'])

In [6]:
df['Year'] = df['datetime'].dt.year
df['Month'] = df['datetime'].dt.month

In [7]:
df['temperature'] = pd.to_numeric(df['temperature'], errors='coerce')
df['dew_point'] = pd.to_numeric(df['dew_point'], errors='coerce')
df['wind_speed'] = pd.to_numeric(df['wind_speed'], errors='coerce')

In [8]:
monthly_avg = df.groupby(['Year', 'Month'])[['temperature', 'dew_point', 'wind_speed']].mean().reset_index()

In [9]:
print(monthly_avg.head())

   Year  Month  temperature  dew_point  wind_speed
0  2020      1    62.716502  37.239774    8.908322
1  2023      1    62.958193  31.813891    7.385030
2  2023      2    72.167414  53.913303    6.491779
3  2023      3    78.921106  56.465273    7.178692
4  2024      1    67.128706  47.402291    5.977089